
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
 * This class was generated by 'kentico-cloud-model-generator-utility' at Sun Sep 09 2018 10:50:06 GMT-0400 (Eastern Daylight Time).
 *
 * Note: You can substitute 'ContentItem' type with another generated class. Generator doesn't have this information available
 * and so its up to you to define relationship between models.
 */
export class Skill extends ContentItem {
    public skillName: Fields.TextField;
    constructor() {
        super({
            propertyResolver: ((fieldName: string) => {
                if (fieldName === 'skill_name') {
                    return 'skillName';
                }
                return fieldName;
            })
        });
    }
}
